CREATE TABLE Orders (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerName NVARCHAR(255) NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    OrderDate DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
ALTER TABLE Orders
ADD Status NVARCHAR(50) NOT NULL DEFAULT 'Pending';
